name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5443:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      mariadb:
        image: mariadb:11
        env:
          MARIADB_ROOT_PASSWORD: root_password
          MARIADB_DATABASE: test
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
        ports:
          - 3307:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "Testpassword123@"
          MSSQL_PID: "Developer"
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Testpassword123@' -C -Q 'SELECT 1' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=10s
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_sqlite, pdo_mysql, pdo_pgsql, pdo_odbc
          coverage: xdebug
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      
      - name: Wait for databases
        run: sleep 15
      
      - name: Run all tests
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: test
          MYSQL_USERNAME: test_user
          MYSQL_PASSWORD: test_password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5443
          POSTGRES_DATABASE: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          MARIADB_HOST: localhost
          MARIADB_PORT: 3307
          MARIADB_DATABASE: test
          MARIADB_USERNAME: test_user
          MARIADB_PASSWORD: test_password
          MSSQL_HOST: localhost
          MSSQL_PORT: 1433
          MSSQL_DATABASE: master
          MSSQL_USERNAME: sa
          MSSQL_PASSWORD: "Testpassword123@"
        run: ./vendor/bin/pest

      - name: Run Laravel pint
        run: ./vendor/bin/pint

      - name: Run php stan analyze
        run: ./vendor/bin/phpstan analyze